[IN-PROGRESS] French - Involving Users in Web Projects for Better, Easier Accessibility
w3c/wai-InvolveUsersAll pull request #25
Opened 2023-10-02 16:36 UTC by remibetin

From @miss-poullon https://github.com/w3c/wai-InvolveUsersAll/pull/24

Fixes https://github.com/w3c/wai-translations/issues/59

2024-06-19 21:10 UTC, miss-poullon requested changes
Thanks for the follow-up and suggestions, Rémi. I’ve spotted a few typos and a spelling mistake. I suggest some changes before publishing. Let me know what you think!

2024-06-19 21:10 UTC, miss-poullon commented on content/index.fr.md
> +Impliquer les utilisateurs tôt dans les projets vous permet de comprendre les problèmes d'accessibilité qu'ils rencontrent dans la vie réelle, telle que la façon dont les personnes en situation de ha
Suggestion for "telle que" : 
"Impliquer les utilisateurs tôt dans les projets vous permet de comprendre les problèmes d'accessibilité qu'ils rencontrent dans la vie réelle, tels que la façon dont les personnes en situation de handicap ou âgées utilisent le Web grâce à des [stratégies d'adaptation](#strategies){:.termref} et des [technologies d'assistance](#at){:.termref}."

cf. [Accorder ou ne pas accorder « tel » - Projet Voltaire](https://www.projet-voltaire.fr/regle-orthographe/regles-accord-singulier-pluriel-adjectif-tel-telle-tels-telles-que/)

2024-06-19 21:10 UTC, miss-poullon commented on content/index.fr.md
> +Cette page vous permet de commencer à révolter les bénéfices d'une **implication des utilisateurs — plus particulièrement de personnes en situation de handicap, et de personnes âgées ayant des besoin
Suggestion for "révolter" (typo) :
"Cette page vous permet de commencer à récolter les bénéfices (...)"

2024-06-19 21:10 UTC, miss-poullon commented on content/index.fr.md
> +Impliquer les utilisateurs tôt dans les projets Web aboutit à de meilleurs produits pour  les utilisateurs, des développements plus efficaces, et d'autres bénéfices pour les parties-prenantes du proj
Suggestion for "parties-prenantes" :
"(...) pour les parties prenantes du projet."

2024-06-19 21:10 UTC, miss-poullon commented on content/index.fr.md
> +Cela bénéficie aux utilisateurs, mais aussi aux parties-prenantes. Par exemple, quand les sites Web voient leur [utilisation augmenter](https://www.w3.org/WAI/business-case/archive/fin#increase-use),
Suggestion for "parties-prenantes" :
"(...) aux parties prenantes."

2024-06-19 21:10 UTC, miss-poullon commented on content/index.fr.md
> +Un critère primordial à prendre en compte lors du recrutement d'utilisateurs est leur expérence dans l'interaction avec le Web. Par exemple, il est compliqué et difficile d'apprendre à utiliser certa
Suggestion for "leur expérence dans l'interaction" (typo):
"(...) leur expérience dans l'interaction (...)

2024-06-20 09:25 UTC, closed without merging

2024-06-20 09:25 UTC, remibetin commented
@miss-poullon Thanks very much Céline for spotting these typos! The content of this resource has been moved. I have therefore re-created this PR at https://github.com/w3c/wai-website/pull/488 and integrated your suggestions!

2024-06-20 09:53 UTC, remibetin commented
@miss-poullon This translation is now published! See https://www.w3.org/WAI/planning/involving-users/fr

Thanks again!